bfs:
	echo "running test file against breadth first search"
	python3 app.py -w "77000" -f test.txt  -sa breadth-first-search -o level-order

dfs-pre:
	echo "running test file against depth first search for pre-order"
	python3 app.py -w "770" -f test.txt  -sa depth-first-search -o pre-order

dfs-post:
	echo "running test file against depth first search for post-order"
	python3 app.py -w "770" -f test.txt  -sa depth-first-search -o post-order

dfs-in:
	echo "running test file against depth first search for in-order"
	python3 app.py -w "770" -f test.txt  -sa depth-first-search -o in-order


binary:
	echo "running test file against binary search"
	python3 app.py -w "770" -f test.txt  -sa binary-search -o level-order